from pathlib import Path
import sys, tempfile, subprocess, json, hashlib, datetime, shutil
ROOT=Path.cwd(); OUT=ROOT/'.playbook-artifacts/delivery-acceptance-20261009/review'; OUT.mkdir(parents=True,exist_ok=True)
FILES=['distribution/desktop/setup_core.py','distribution/desktop/desktop_setup.py','distribution/desktop/desktop_runtime.py','distribution/desktop/build.py','distribution/desktop/test_setup.py','tools/playbook_environment.py','tools/solution_record.py','plugins/playbook-native/skills/playbook/SKILL.md','plugins/playbook-native/skills/playbook/references/review.md','plugins/playbook-native/skills/playbook/references/setup.md','plugins/playbook-native/skills/playbook/references/environment.md','plugins/playbook-native/skills/playbook/references/lifecycle/discover.md','plugins/playbook-native/skills/playbook/references/lifecycle/verify.md','distribution/native/build.py','distribution/native/sync_runtime.py','.github/workflows/native-checks.yml']
def identity(): return {f:hashlib.sha256((ROOT/f).read_bytes()).hexdigest() for f in FILES}
before=identity(); head=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(); commands=[]
def run(name,args):
 start=datetime.datetime.now(datetime.timezone.utc).isoformat(); r=subprocess.run(args,cwd=ROOT,capture_output=True,text=True,encoding='utf-8',timeout=180)
 (OUT/(name+'.stdout.txt')).write_text(r.stdout,encoding='utf-8'); (OUT/(name+'.stderr.txt')).write_text(r.stderr,encoding='utf-8')
 commands.append({'name':name,'argv':args,'exit_code':r.returncode,'start_utc':start,'end_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}); return r
python=str(ROOT/'.venv-delivery-20261009/bin/python')
run('initial-desktop-tests',[python,'-m','unittest','discover','-s','distribution/desktop','-p','test_*.py','-v'])
run('initial-vnext-tests',[python,'-m','unittest','discover','-s','tests/vnext','-v'])
sys.path[:0]=[str(ROOT/'distribution/desktop'),str(ROOT/'distribution/native')]
import setup_core, desktop_setup, build
with tempfile.TemporaryDirectory(prefix='delivery-review-initial-') as d:
 p=Path(d); built=build.build(p/'kit'); kit=setup_core.Kit.load(Path(built['archive']),built['sha256']); root=p/'original'; root.mkdir(); (root/'notes.txt').write_text('Owner data')
 bad=run('managed-documented-order',[python,str(ROOT/'distribution/desktop/desktop_setup.py'),'--kit',built['archive'],'--sha256',built['sha256'],'helper','review','--root',str(root),'run','--help'])
 good=run('managed-correct-order',[python,str(ROOT/'distribution/desktop/desktop_setup.py'),'--kit',built['archive'],'--sha256',built['sha256'],'helper','review','run','--root',str(root),'--help'])
 setup_core.apply(setup_core.plan(root,kit,'install',['playbook-helper']),consent=True); moved=p/'moved'; shutil.copytree(root,moved)
 cases={'copied_before':setup_core.installation_status(moved)}
 cases['copied_update']=setup_core.apply(setup_core.plan(moved,kit,'update',['playbook-helper']),consent=True); cases['copied_after_update']=setup_core.installation_status(moved)
 (moved/setup_core.JOURNAL).unlink(); cases['missing_journal_before']=setup_core.installation_status(moved)
 cases['missing_journal_remove']=setup_core.apply(setup_core.plan(moved,kit,'remove'),consent=True); cases['owner_data_after']=(moved/'notes.txt').read_text()
 (OUT/'initial-journal-reproduction.json').write_text(json.dumps(cases,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
after=identity()
data={'schema':'playbook.independent-platform-review.v1','status':'CHANGES_REQUESTED','adapter':'platform_collaboration_read_only','native_role_runner':'NOT_RUN','reviewer':'/root/delivery_final_review','model_identity':'inherited platform agent; provider billing/model telemetry unavailable','head_at_start':head,'baseline':'de2478f4a3fdffb4c568898f37a078500f203b8a','reviewed_file_sha256':before,'source_changed_during_commands':[f for f in before if before[f]!=after[f]],'commands':commands,'findings':[{'id':'DELIVERY-P2-01','severity':'P2','file':'plugins/playbook-native/skills/playbook/references/review.md','line':38,'title':'Managed review example puts --root before the run subcommand','observed':'Exact packaged helper argv with --help exits2; corrected order exits0. No inference invoked.','fix':'Use helper review run --profile native --root <project> ... once, and parse the literal packaged documentation command offline.'},{'id':'DELIVERY-P2-02','severity':'P2','file':'distribution/desktop/setup_core.py','line':375,'title':'Mutation path ignores journal schema/root/missing-state gate used by diagnostics','observed':'Copied project has invalid/interrupted doctor status; update returns unchanged and remains interrupted. Removing journal permits remove despite unknown/interrupted diagnosis. Owner notes retained.','fix':'Unify journal identity/status validation for plan/apply and diagnostic; missing journal for installed state is blocked; unaffected brand-new install remains valid.'}],'open_p0':0,'open_p1':0,'open_p2':2,'limits':['Technical Linux VPS review, not Windows/macOS/clean-machine acceptance.','No real participant, repeated field use, external preview, Cloudflare account/claim, model inference or provider login was performed by this reviewer.','This is platform read-only independent review, not Native Role Runner evidence.','No source edits, credential reads, paid API calls or recursive reviewer.'],'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}
(OUT/'initial.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
(OUT/'initial.md').write_text('''# Independent Delivery review — initial\n\nVerdict: CHANGES REQUESTED. Two confirmed P2 correctness issues; no confirmed P0/P1 found in this scope.\n\nReviewer `/root/delivery_final_review` used a separate platform collaboration session in read-only source scope. This is not a Native Role Runner run. No inference, paid API, credentials, account login, external publication or recursive review was invoked. Temporary project fixtures and review artifacts were the only reviewer writes.\n\n1. `references/review.md` managed helper command passes `--root` before `run`; actual packaged entrypoint rejects it (exit 2) before review. The corrected ordering passes offline `--help` (exit 0).\n2. Desktop diagnostic rejects foreign-root/missing installation journal as interrupted, but plan/apply ignore those same conditions. A copied project returns `unchanged` on update yet remains interrupted, and a missing-journal managed installation can be removed. No owner data loss occurred in the reproduction. Unify the mutation and diagnostic journal checks.\n\nObserved checks: 18 Desktop mechanism tests and 50 vNext tests passed; exact logs and argv/status are in `initial.json` and adjacent stdout/stderr. Source identities are included in `reviewed_file_sha256`; any changes during commands are explicit.\n\nThe existing master Discover/Verify files are preserved (no diff from de2478f). New environment/evidence helpers retain presence-versus-execution, local identity-versus-quality and authorization boundaries. Runtime-pointer/final-journal-write regression tests pass. Frozen files and public historical evidence are not regenerated.\n\nLimits: Linux technical tests and artifact source audit do not prove clean-machine GUI, Windows/macOS acceptance of this final source, real people, field benefit, external preview or completed Cloudflare claim. A final independent recheck is required after fixes and the final acceptance documentation.\n''',encoding='utf-8')
print(json.dumps({'report':str(OUT/'initial.md'),'findings':str(OUT/'initial.json'),'bad_order_rc':bad.returncode,'good_order_rc':good.returncode,'drift':data['source_changed_during_commands']},indent=2))
