from pathlib import Path
import sys, tempfile, subprocess, json, hashlib, datetime, shutil, importlib.util
ROOT=Path.cwd(); OUT=ROOT/'.playbook-artifacts/delivery-acceptance-20261009/review'; OUT.mkdir(parents=True,exist_ok=True)
ORIGINAL=Path('/tmp/playbook-delivery-audit-QDI6NT/repo/distribution/desktop/setup_core.py')
assert hashlib.sha256(ORIGINAL.read_bytes()).hexdigest()=='5f2e7def242ed9bbcf4641cca186cc17f17a927d799730a063735b431334fdb9'
def load(name,path):
 spec=importlib.util.spec_from_file_location(name,path); m=importlib.util.module_from_spec(spec); sys.modules[name]=m; spec.loader.exec_module(m); return m
setup_core=load('review_initial_setup_core',ORIGINAL)
native=load('review_initial_native_build',ROOT/'distribution/native/build.py')
python=str(ROOT/'.venv-delivery-20261009/bin/python'); commands=[]
def run(name,args):
 r=subprocess.run(args,cwd=ROOT,capture_output=True,text=True,encoding='utf-8',timeout=30)
 (OUT/(name+'.stdout.txt')).write_text(r.stdout,encoding='utf-8'); (OUT/(name+'.stderr.txt')).write_text(r.stderr,encoding='utf-8'); commands.append({'name':name,'argv':args,'exit_code':r.returncode}); return r
with tempfile.TemporaryDirectory(prefix='delivery-review-original-findings-') as d:
 p=Path(d); built=native.build(p/'kit'); kit=setup_core.Kit.load(Path(built['archive']),built['sha256']); root=p/'original'; root.mkdir(); (root/'notes.txt').write_text('Owner data')
 bad=run('managed-documented-order',[python,str(ROOT/'distribution/desktop/desktop_setup.py'),'--kit',built['archive'],'--sha256',built['sha256'],'helper','review','--root',str(root),'run','--help'])
 good=run('managed-correct-order',[python,str(ROOT/'distribution/desktop/desktop_setup.py'),'--kit',built['archive'],'--sha256',built['sha256'],'helper','review','run','--root',str(root),'--help'])
 setup_core.apply(setup_core.plan(root,kit,'install',['playbook-helper']),consent=True); moved=p/'moved'; shutil.copytree(root,moved)
 cases={'initial_reviewed_setup_core':str(ORIGINAL),'sha256':hashlib.sha256(ORIGINAL.read_bytes()).hexdigest(),'reproduction_scope':'Exact preserved pre-P2-journal-fix implementation; canonical current kit used only as project payload. Initial behavior was also observed in integrated source before root edits.','copied_before':setup_core.installation_status(moved)}
 cases['copied_update']=setup_core.apply(setup_core.plan(moved,kit,'update',['playbook-helper']),consent=True); cases['copied_after_update']=setup_core.installation_status(moved)
 (moved/setup_core.JOURNAL).unlink(); cases['missing_journal_before']=setup_core.installation_status(moved)
 cases['missing_journal_remove']=setup_core.apply(setup_core.plan(moved,kit,'remove'),consent=True); cases['owner_data_after']=(moved/'notes.txt').read_text()
 (OUT/'initial-journal-reproduction.json').write_text(json.dumps(cases,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
FILES=['distribution/desktop/setup_core.py','distribution/desktop/desktop_setup.py','distribution/desktop/desktop_runtime.py','distribution/desktop/build.py','distribution/desktop/test_setup.py','tools/playbook_environment.py','tools/solution_record.py','plugins/playbook-native/skills/playbook/SKILL.md','plugins/playbook-native/skills/playbook/references/review.md','plugins/playbook-native/skills/playbook/references/setup.md','plugins/playbook-native/skills/playbook/references/environment.md','plugins/playbook-native/skills/playbook/references/lifecycle/discover.md','plugins/playbook-native/skills/playbook/references/lifecycle/verify.md','distribution/native/build.py','distribution/native/sync_runtime.py','.github/workflows/native-checks.yml']
identities={f:hashlib.sha256((ROOT/f).read_bytes()).hexdigest() for f in FILES}; identities['distribution/desktop/setup_core.py']=hashlib.sha256(ORIGINAL.read_bytes()).hexdigest(); original_review_doc=subprocess.check_output(['git','show','2225a3f:plugins/playbook-native/skills/playbook/references/review.md']); identities['plugins/playbook-native/skills/playbook/references/review.md']=hashlib.sha256(original_review_doc).hexdigest()
data={'schema':'playbook.independent-platform-review.v1','status':'CHANGES_REQUESTED','adapter':'platform_collaboration_read_only','native_role_runner':'NOT_RUN','reviewer':'/root/delivery_final_review','model_identity':'inherited platform agent; provider billing/model telemetry unavailable','reviewed_head':'2225a3f','baseline':'de2478f4a3fdffb4c568898f37a078500f203b8a','reviewed_file_sha256':identities,'identity_note':'setup_core identity is exact preserved original applied Desktop patch; review.md identity is integrated pre-root-fix commit. Other identities are current sources read during review. No fabricated uniform snapshot.','commands':commands,'test_observations':[{'command':[python,'-m','unittest','discover','-s','distribution/desktop','-p','test_*.py','-v'],'observed':'18 tests PASS before P2 fixes; later captured initial-desktop-tests log is already root-updated followup source.'},{'command':[python,'-m','unittest','discover','-s','tests/vnext','-v'],'observed':'50 tests PASS before P2 fixes.'}],'findings':[{'id':'DELIVERY-P2-01','severity':'P2','file':'plugins/playbook-native/skills/playbook/references/review.md','line':38,'title':'Managed review example puts --root before the run subcommand','observed':'Actual packaged helper argv with --help exits2; corrected order exits0. No inference invoked.','fix':'Use helper review run --profile native --root <project> ... once; parse literal packaged documentation command offline.'},{'id':'DELIVERY-P2-02','severity':'P2','file':'distribution/desktop/setup_core.py','line':375,'title':'Mutation path ignores journal schema/root/missing-state gate used by diagnostics','observed':'Copied project has invalid/interrupted doctor status; update returns unchanged and remains interrupted. Removing journal permits remove despite unknown/interrupted diagnosis. Owner notes retained.','fix':'Unify journal identity/status validation for plan/apply and diagnostic; missing journal for installed state is blocked; unaffected new install remains valid.'}],'open_p0':0,'open_p1':0,'open_p2':2,'limits':['Technical Linux VPS review, not Windows/macOS/clean-machine acceptance.','No real participant, repeated field use, external preview, Cloudflare account/claim, model inference or provider login was performed by this reviewer.','Platform read-only independent review, not Native Role Runner evidence.','No source edits, credential reads, paid API calls or recursive reviewer.','An aborted initial evidence capture accidentally selected Desktop builder due ambiguous Python build module name, started local freezer under its own temporary directory, and was stopped; it is not an acceptance run. Corrected capture explicitly imports the canonical Native builder.'],'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}
(OUT/'initial.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
(OUT/'initial.md').write_text('''# Independent Delivery review — initial\n\nVerdict: CHANGES REQUESTED. Two confirmed P2 correctness issues; no confirmed P0/P1 found in this scope.\n\nReviewer `/root/delivery_final_review` used a separate platform collaboration session in read-only source scope. This is not a Native Role Runner run. No inference, paid API, credentials, account login, external publication or recursive review was invoked. Temporary project fixtures and review artifacts were the only reviewer writes.\n\n1. Integrated `references/review.md` managed command passes `--root` before `run`; the actual packaged entrypoint rejects that argv (exit 2) before review. Corrected ordering passes offline `--help` (exit 0).\n2. Desktop diagnostic rejects foreign-root/missing installation journal as interrupted, but plan/apply ignore those same conditions. A copied project returns `unchanged` on update yet remains interrupted; a missing-journal installation can be removed. No owner-data loss occurred. Unify mutation/diagnostic journal validation.\n\nObserved before fixes: 18 Desktop mechanism tests and 50 vNext tests PASS. Exact reproduction commands, statuses and source identity notes are in `initial.json`; journal fixture outcomes in `initial-journal-reproduction.json`. Root edits started during capture; initial setup_core reproduction therefore uses the exact preserved pre-P2-fix bytes, not a fabricated uniform snapshot. Later test capture is explicitly follow-up source.\n\nCurrent master Discover/Verify files are preserved (no diff from de2478f). New environment/evidence helpers retain presence-versus-execution, identity-versus-quality and authorization boundaries. Runtime-pointer/final-journal-write regressions pass. Frozen historical evidence was not regenerated.\n\nLimits: Linux technical tests and source audit do not prove clean-machine GUI, Windows/macOS final-source acceptance, real users, field benefit, external preview or completed Cloudflare claim. Final independent recheck is pending final fixes/documentation.\n''',encoding='utf-8')
print(json.dumps({'report':str(OUT/'initial.md'),'findings':str(OUT/'initial.json'),'bad_order_rc':bad.returncode,'good_order_rc':good.returncode},indent=2))
